### ISSUE TITLE
Inconsistent name space with the rest of palantir dropwizard bundles

### ISSUE THREAD

**Issue by qinfchen** [palantir/encrypted-config-value#12]
This bundle uses `com.palantir.config.crypto` and it is not consistent with the name space the rest of palantir dropwizard bundles (`com.palantir.dropwizard`).

**Comment by markelliot** [comment]
I don't think it's wise we namespace all dropwizard bundles under that one package.

**Comment by jmcampanini** [comment]
should we use a standard prefix (so it's `com.palantir.something.*`)?

also curious if this should apply to the publish `groupId`

**Comment by markelliot** [comment]
I think it'd be a lot clearer if the bundles live in namespaces relative to what they do rather than a global namespace. e.g, we have a thing called "foo", it's confusing to me that when I need to depend on foo, that I need to pull "c.p.foo:proj" and also "c.p.dropwizard:foo". I'd rather see "c.p.foo:dropwizard-foo". This makes browsing Artifactory a lot simpler; for instance.

As an aside, publishing to JCenter via Bintray requires a common root, so for some OSS projects we produce, I think forcing bundles into different groups might make JCenter mirroring impossible.

**Comment by jmcampanini** [comment]
:+1: works for me

**Comment by bavardage** [comment]
cool, will close for now
