### ISSUE TITLE
IV size for AES GCM does not match NIST recommendations

### ISSUE THREAD

**Issue by sfackler** [palantir/encrypted-config-value#55]
From http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf:

> For IVs, it is recommended that implementations restrict support to the length of 96 bits, to
promote interoperability, efficiency, and simplicity of design.

However, a 256 bit IV is used here: https://github.com/palantir/encrypted-config-value/blob/develop/encrypted-config-value/src/main/java/com/palantir/config/crypto/algorithm/AesAlgorithm.java#L43

**Comment by bavardage** [comment]
@markelliot @bschimpf do either of you remember why we went with the 256 bit IST? (it may have just been me naively choosing a value)

**Comment by markelliot** [comment]
I didn't take note of this when we started, would be interested to know what we do in hadoop-crypto. @ellisjoe, want to weigh in?

**Comment by bavardage** [comment]
seems we use 16 byte if I'm reading this correctly https://github.com/palantir/hadoop-crypto/blob/910358236008359784808dfe208a24b622a7e812/crypto-core/src/main/java/com/palantir/crypto2/cipher/AesCtrCipher.java#L120

**Comment by sfackler** [comment]
That's AES CTR rather than GCM, though.

**Comment by bavardage** [comment]
yep, hadoop crypto only does ctr/cbc

**Comment by ellisjoe** [comment]
Yep. AES/CTR and AES/CBC need IVs that are the same length as the block size.

**Comment by rahul1** [comment]
+1 I faced an issue related to this, and it blocked me for 2 full days. Part of the issue was that the original exception from Java Security was being swallowed, so I couldn't see the orignal error message. After I found it, I could use the SO post below to solve the issue

http://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters

**Comment by markelliot** [comment]
This isn't really related. We're going to continue defaulting to 256 bit keys, but smaller IVs.

On Mar 20, 2017, at 5:41 PM, rahul1 <notifications@github.com<mailto:notifications@github.com>> wrote:


+1 I faced an issue related to this, and it blocked me for 2 full days. Part of the issue was that the original exception from Java Security was being swallowed, so I couldn't see the orignal error message. After I found it, I could use the SO post below to solve the issue

http://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters[stackoverflow.com]<https://urldefense.proofpoint.com/v2/url?u=http-3A__stackoverflow.com_questions_6481627_java-2Dsecurity-2Dillegal-2Dkey-2Dsize-2Dor-2Ddefault-2Dparameters&d=DwMFaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=Vp81aOxWZvuVgVK_wp-VF3pIYG92B19LcCw6XKeYC0U&m=W0r4BSB7S3IDEEI95lR-rhlZ4hatLVP5Xn6EKu7hTWs&s=9JTeFUH0rwGkDyB-oX2BngDEv6zqi_zyw_SnM9SGqw0&e=>

**Comment by nmiyake** [comment]
Noticed this today while taking a crack at cleaning up our Go implementation of encrypted-config-value. Can confirm that, from everything I've seen, 12-byte IV length seems to be standard for GCM:

http://crypto.stackexchange.com/a/26787

And in Go's implementation:

```go
gcmStandardNonceSize = 12

// NewGCM returns the given 128-bit, block cipher wrapped in Galois Counter Mode
// with the standard nonce length.
func NewGCM(cipher Block) (AEAD, error) {
	return NewGCMWithNonceSize(cipher, gcmStandardNonceSize)
}
```
